### PR TITLE
Fix out-of-bound fetching at the end of VASTROs

### LINKED ISSUE #82: Index and chunk size overflow on VASTRO's bitmap
This happened with a file of size `64623045 Bytes`. When playing a video as VASTRO ad the end `codacon` throws;

```
Fetch Earth.mov [63109] ( 20:45:15 )  
fetching (Earth.mov) 0% (0Bs/18446744073709523397Bs) [64651264 - 64623045]
```

Note that the size of the chunk is supposly `18446744073709523397Bs`. Maybe a negative number?

Apparently it's trying to access the `n`th block. In this case the `63109`th block.

### PR DESCRIPTION
**Pull request by pjcuadra**
closes #82

### CODE REVIEW

File: coda-src/venus/fso_cachefile.cc [hunk 1]
```diff
@@ -575,35 +575,54 @@ CacheChunkList::~CacheChunkList()
...
 
-        if ((i + 1 == end_b) || cached_chunks->Value(i + 1)) {
-            return (CacheChunk(holestart * CacheChunkBlockSize, holesize));
-        }
+    hole_size = ccblocks_to_bytes(hole_end_idx - hole_start_idx - 1);
+
+    /* If the hole ends at EOF and it has a tail */
+    if (hole_end_idx == nblocks && nblocks_full != nblocks) {
+        /* Add the tail */
+        uint64_t tail = length - ccblocks_to_bytes(nblocks - 1);
```
Comment (jaharkes) [inline coda-src/venus/fso_cachefile.cc]: should this be ccblocks_to_bytes(nblocks_full -1) ?

Comment (jaharkes) [reply coda-src/venus/fso_cachefile.cc]: actually, nblocks-1 should be ok, at this point I believe the following holds true
 nblocks-1 == nblocks_full
which makes ccblocks_to_bytes(nblocks-1) the length rounded down to the start of the chunk
